### ISSUE TITLE
Type 'Loader' is not assignable to type typescript error

### ISSUE THREAD

**Issue by tiwka19** [AlphaJack/astro-sheet-loader#1]
![image](https://github.com/user-attachments/assets/f8ec2ca6-9e2f-4553-add0-7ca5d2812d55)

**Comment by AlphaJack** [comment]
Thanks for the report, looks like the Loader type from Astro had a breaking change between Astro 4.14 and 5.

I rebuilt the extension with the new Astro version and the error is gone.

Version [1.0.5](https://www.npmjs.com/package/astro-sheet-loader) is now available from npm.
